name: Docker

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        name: Check out code

      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          ecr: false
          logout: true
                
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: dennyherbrich/weather-app
          tags: |
              type=schedule
              type=ref,event=branch
              type=ref,event=tag
              type=ref,event=pr
              type=raw,value=latest,enable=${{ github.ref == format('refs/heads/{0}', 'main') }}
          # Add latest tag ^
      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          # Don't push on pull requests
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
